version: '3.7'

services:
  currency_app:
    container_name: currency_app
    image: currency_app_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "16000:8000"
# Для примера контейнер redis
#  app_redis:
#    image: redis:6.2-alpine
#    hostname: redis
#    container_name: app_redis_1
#    command:
#      - 'redis-server'
#      - '--requirepass myStrongPassword'
#    ports:
#      - 36379:6379
# И пример nginx
#  nginx:
#    image: nginx:1.23.2-alpine
#    restart: always
#    depends_on:
#      - backend
#    volumes:
#      - ./frontend/:/usr/share/nginx/html/
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - static_value:/var/html/static/
#    ports:
#      - "80:80"
#    env_file:
#      - .env
